name: Deploy JWS Saharanpur

on:
  push:
    branches:
      - main
    paths:
      - "janhitcampus/janhit_world_school_saharanpur/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/jwssre.yml"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build JWS Saharanpur
        run: npm run build:jwssre

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./janhitcampus/janhit_world_school_saharanpur/dist s3://jwssre.janhitgroup.com --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2Q8E10L0004HD \
            --paths "/*"